// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CD5B6eJjUAUjejh2I0eFLil16_-q5Nw',
    appId: '1:419307715089:web:0ebdfff5ba263332efcfb0',
    messagingSenderId: '419307715089',
    projectId: 'coursecraft-3b970',
    authDomain: 'coursecraft-3b970.firebaseapp.com',
    databaseURL: 'https://coursecraft-3b970-default-rtdb.firebaseio.com',
    storageBucket: 'coursecraft-3b970.appspot.com',
    measurementId: 'G-B301CKFQYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1Ld2x_Vd0MArjFsL82Tl0-l54WRU_4Q',
    appId: '1:419307715089:android:5850ce0601f7bb77efcfb0',
    messagingSenderId: '419307715089',
    projectId: 'coursecraft-3b970',
    databaseURL: 'https://coursecraft-3b970-default-rtdb.firebaseio.com',
    storageBucket: 'coursecraft-3b970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNyXZj814nRB2FHnFLJSVv3cTpEj1ZBE',
    appId: '1:419307715089:ios:b662320b9974b643efcfb0',
    messagingSenderId: '419307715089',
    projectId: 'coursecraft-3b970',
    databaseURL: 'https://coursecraft-3b970-default-rtdb.firebaseio.com',
    storageBucket: 'coursecraft-3b970.appspot.com',
    iosBundleId: 'com.example.coursecraftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNyXZj814nRB2FHnFLJSVv3cTpEj1ZBE',
    appId: '1:419307715089:ios:b662320b9974b643efcfb0',
    messagingSenderId: '419307715089',
    projectId: 'coursecraft-3b970',
    databaseURL: 'https://coursecraft-3b970-default-rtdb.firebaseio.com',
    storageBucket: 'coursecraft-3b970.appspot.com',
    iosBundleId: 'com.example.coursecraftApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CD5B6eJjUAUjejh2I0eFLil16_-q5Nw',
    appId: '1:419307715089:web:9ec2747367e3c988efcfb0',
    messagingSenderId: '419307715089',
    projectId: 'coursecraft-3b970',
    authDomain: 'coursecraft-3b970.firebaseapp.com',
    databaseURL: 'https://coursecraft-3b970-default-rtdb.firebaseio.com',
    storageBucket: 'coursecraft-3b970.appspot.com',
    measurementId: 'G-REC8WJTDXC',
  );
}
